# Generated by Django 5.2 on 2025-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cca2', models.CharField(max_length=255)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
